### ISSUE TITLE
Inventory close button not working

### ISSUE THREAD

**Issue by brunosemfio** [Hexworks/caves-of-zircon-tutorial-old#1]
<img width="1292" alt="Captura de Tela 2019-07-07 às 01 25 29" src="https://user-images.githubusercontent.com/22257786/60763980-364a9580-a056-11e9-981b-722258aa471c.png">

Close button isn't clickable but focus tab works

**Comment by bruce-forte** [comment]
This bug is fixed in [2019.1.2-PREVIEW](https://jitpack.io/#org.hexworks/zircon/2019.1.2-PREVIEW). The problem was that when beta features are enabled the bounds check for componens was relaxed which lead to weird behavior like this. I'm going to fix the tutorial as well not to have this problem. In this particular case the `VBox` holding the items overlapped with the `[Close]` button so you were not able to click it.

Anyway, thanks for reporting it! Feel free to chime in on our [Discord Server](https://discordapp.com/invite/vSNgvBh) as well if you have questions regarding the tutorial.
